// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGckaMboE9NhSP7VGrd3ppVk5A7EPVs9c',
    appId: '1:542020034291:web:e364e75f1bfa5e4004e186',
    messagingSenderId: '542020034291',
    projectId: 'desserts-97d61',
    authDomain: 'desserts-97d61.firebaseapp.com',
    storageBucket: 'desserts-97d61.appspot.com',
    measurementId: 'G-8RNP92BHRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3YBYRQaOagfdo3aB9aisoIis_ry7vqxk',
    appId: '1:542020034291:android:d2cbebb1a93bc5f004e186',
    messagingSenderId: '542020034291',
    projectId: 'desserts-97d61',
    storageBucket: 'desserts-97d61.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAEs9-IIhiTLCM7VY6RWjymUPCuSZPGXsA',
    appId: '1:542020034291:ios:facdc0beeb9e387d04e186',
    messagingSenderId: '542020034291',
    projectId: 'desserts-97d61',
    storageBucket: 'desserts-97d61.appspot.com',
    iosClientId: '542020034291-eep387i2dcfjg3vjuntg87fatjek5so4.apps.googleusercontent.com',
    iosBundleId: 'com.example.desserts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAEs9-IIhiTLCM7VY6RWjymUPCuSZPGXsA',
    appId: '1:542020034291:ios:facdc0beeb9e387d04e186',
    messagingSenderId: '542020034291',
    projectId: 'desserts-97d61',
    storageBucket: 'desserts-97d61.appspot.com',
    iosClientId: '542020034291-eep387i2dcfjg3vjuntg87fatjek5so4.apps.googleusercontent.com',
    iosBundleId: 'com.example.desserts',
  );
}
